import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router';
import { Swiper, SwiperSlide } from "swiper/react";
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/autoplay";
import { Pagination, Autoplay } from "swiper";
import { TextField, Button, MenuItem } from '@mui/material'
import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider'
import { DatePicker } from '@mui/x-date-pickers/DatePicker'
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs'
import dayjs from 'dayjs'
import * as yup from "yup"
import { Controller, useForm } from 'react-hook-form'
import { yupResolver } from '@hookform/resolvers/yup'
import Swal from 'sweetalert2'

const regisSchema = yup.object().shape({
    fullName: yup.string().required(),
    address: yup.string().required(),
    phone: yup.string().required(),
    email: yup.string().email().required(),
    password: yup.string().required()
})

const Register = () => {
    const { control, handleSubmit, formState: { errors } } = useForm({ resolver: yupResolver(regisSchema) })
    const handleLogin = (data) => {
        console.log(data)
    }
    const router = useRouter()
  return (
    <>
    <Head>
        <title>Register - Account</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div className='w-full flex overflow-auto max-h-[100vh] items-center flex-col justify-start'>
        <div className='w-full h-[100vh] flex items-end justify-start'>
            <div className='flex-[0_0_auto] w-[50%] h-full flex relative self-center items-start flex-col justify-start'>
            {/* <img src='/playground_assets/logo%20black.svg' alt='' loading='lazy' className='top-[27px] left-[49px] w-[100px] absolute object-cover cursor-pointer'/> */}
            <button onClick={() => router.push('/')} className='ml-8 mt-4 p-1.5 text-2xl font-medium'>
                <span>SARI</span><span className='ml-1 text-[#F46A06]'>GADING</span>
                {/* <span className='sr-only'>Depot Sarigading</span>
                <Image src='/sarigading.png' className='w-auto h-16' alt='' width='100' height='100'/> */}
              </button>
                <div className='w-[90%] h-auto m-auto flex self-center items-center flex-col justify-center'>
                    <h1 className='text-[20px] self-center my-4 py-2 font-bold'>Create Account</h1>
                    <span className='text-[#7a7c85] self-center font-medium mb-8'>Get started with an account on SARI GADING</span>
                    <form onSubmit={handleSubmit(handleLogin)} className='gap-8 w-[50%] h-auto flex max-w-[50%] self-center mb-4 flex-col'>
                    <div className='my-1 mx-2 flex flex-col gap-y-2'>
                            <div>
                            <Controller
                            name='fullName'
                            control={control}
                            defaultValue=''
                            render={({ field }) => (
                                <TextField
                                {...field}
                                margin='dense'
                                placeholder='Fullname'
                                fullWidth
                                error={!!errors.fullName}
                                helperText={errors.fullName?.message}
                                />
                            )}
                            />
                            </div>

                            <div>
                            <Controller
                            name='address'
                            control={control}
                            defaultValue=''
                            render={({ field }) => (
                                <TextField
                                {...field}
                                margin='dense'
                                placeholder='Home Address'
                                fullWidth
                                error={!!errors.address}
                                helperText={errors.address?.message}
                                />
                            )}
                            />
                            </div>

                            <div>
                            <Controller
                            name='phone'
                            control={control}
                            defaultValue=''
                            render={({ field }) => (
                                <TextField
                                {...field}
                                margin='dense'
                                placeholder='Phone Number'
                                fullWidth
                                error={!!errors.phone}
                                helperText={errors.phone?.message}
                                />
                            )}
                            />
                            </div>

                            <div>
                            <Controller
                            name='email'
                            control={control}
                            defaultValue=''
                            render={({ field }) => (
                                <TextField
                                {...field}
                                margin='dense'
                                placeholder='Email'
                                fullWidth
                                error={!!errors.email}
                                helperText={errors.email?.message}
                                />
                            )}
                            />
                            </div>

                            <div>
                            <Controller
                            name='password'
                            control={control}
                            defaultValue=''
                            render={({ field }) => (
                                <TextField
                                {...field}
                                type='password'
                                margin='dense'
                                placeholder='Password'
                                fullWidth
                                error={!!errors.password}
                                helperText={errors.email?.password}
                                />
                            )}
                            />
                            </div>
                        </div>
                        {/* <input type='email' placeholder='Email' className='h-[60px] border border-black rounded-[7px] p-6'/>
                        <input type='password' placeholder='Password' className='h-[60px] border border-black rounded-[7px] p-6'/> */}
                    <button type='submit' className='text-white w-[50%] h-[60px] self-center my-4 font-semibold rounded-[7px] bg-[#F46A06] hover:bg-[#c4590d]'>Register</button>
                    </form>
                    
                    <div className='flex self-center my-8 items-start'>
                        <span className='self-center font-medium text-[#7a7c85]'>
                            already register
                        </span>
                        <span className='text-[#fa9a55] self-center font-bold cursor-pointer'
                        >Login now</span>
                    </div>
                </div>
            </div>
            <div className='w-[50%] h-full flex self-center items-start justify-center border-l'>
                <Swiper pagination={false} modules={[Pagination, Autoplay]} autoplay={true} className="mySwiper">
                    <SwiperSlide>
                        <img src='/slider1.jpg'/>
                    </SwiperSlide>

                    <SwiperSlide>
                        <img src='/slider2.jpg'/>
                    </SwiperSlide>

                    <SwiperSlide>
                        <img src='/slider3.jpg'/>
                    </SwiperSlide>
                </Swiper>
            </div>
        </div>
    </div>
    </>
  )
}

export default Register