import React, { useState, useEffect } from "react";
import axios from "axios";
import Head from "next/head";
import { useRouter } from "next/router";
import { MdLogin, MdAdd } from "react-icons/md";
import { Card, CardContent, CardActions, CardMedia } from "@mui/material";
// import Image from "next/image";
// import ImageDisplay from "@/components/ImageDisplay";
// Keren bang
const AdminDashboard = () => {
  const router = useRouter();
  // Fetch data from API and store it in a state variable
  const [data, setData] = useState([]);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const response = await axios.get("http://localhost:8000/tampil");
        console.log(response.data);
        setData(response.data.values);
      } catch (error) {
        console.error(error);
      }
    };

    fetchData();
  }, []);

  const CombinedImage = ({ imageData }) => {
    const [imageSrc, setImageSrc] = useState(null);

    useEffect(() => {
      const loadImage = () => {
        const image = new Image();
        image.src = `data:image/jpeg;base64,${imageData}`;
        setImageSrc(image);
      };

      loadImage();
    }, [imageData]);

    if (!imageSrc) {
      return null;
    }

    return (
      <div className="flex justify-center h-[50%] my-4">
        <img src={imageSrc.src} width={200} height={100} alt="Combined Image"/>
      </div>
    );
  };
  return (
    <>
      <Head>
        <title>Depot Sari Gading</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
      <header className="bg-white">
          <nav className="mx-auto flex max-w-7xl items-center justify-between p-6 lg:px-8">
            <div className="flex">
              <button
                onClick={() => router.push("/")}
                className=" -m-1.5 p-1.5 text-2xl font-medium"
              >
                <span>DASHBOARD</span>
                <span className="ml-1 text-[#F46A06]">ADMIN</span>
                {/* <span className='sr-only'>Depot Sarigading</span>
                <Image src='/sarigading.png' className='w-auto h-16' alt='' width='100' height='100'/> */}
              </button>
            </div>
            {/* <div className='flex lg:hidden'>
              <button
              type='button'
              className='-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700'
              >
                <span className='sr-only'>Open main menu</span>
                <GiHamburgerMenu className='h-6 w-6' aria-hidden='true'/>
              </button>
            </div> */}

            {/* <button
              onClick={() => router.push("/login")}
              className="text-lg flex items-center mx-4 font-semibold leading-6 text-gray-900 hover:text-[#F46A06]"
            >
              <MdLogin className="mx-1" />
              Logout
            </button> */}
          </nav>
        </header>
        <div className="flex flex-col w-full h-full items-center gap-2 justify-center">
          <h1 className="font-medium text-2xl">Menu Table</h1>
          <div className="flex w-[50%] justify-end">
            <button className="flex items-center text-white font-semibold p-[8px_16px] rounded-lg bg-green-600"
            onClick={() => router.push("/tambah")}
            >
              <MdAdd/>
              Add
            </button>
          </div>
          <div className="w-[60%] h-auto grid grid-cols-3 gap-4 my-4">
            {data.map((menu) => {
              return (
                <>
              <Card key={menu.id_menu} sx={{ minWidth: 300, minHeight: 600}} className="drop-shadow-md">
                <CombinedImage
                  imageData={Buffer.from(menu.gambar.data).toString("base64")}/>
              <CardContent>
                <h1>{menu.nama_menu}</h1>
              </CardContent>
              <CardActions className="flex justify-center mt-2">
                <button className="bg-gray-300 text-lg font-medium p-[10px_18px] w-[220px] rounded-lg">Update</button>
              </CardActions>
              <CardActions className="flex justify-center">
                <button className="bg-red-600 text-lg font-medium p-[10px_18px] w-[220px] rounded-lg">Delete</button>
              </CardActions>
            </Card>
                </>
              )
            })}
          </div>
        </div>
      </div>
    </>
    // <div>
    //   <h1>Dashboard Admin</h1>
    //   <table>
    //     <thead>
    //       <tr>
    //         <th>ID</th>
    //         <th>Name</th>
    //         <th>Price</th>
    //         <th>Stock</th>
    //         <th>Image</th>
    //       </tr>
    //     </thead>
    //     <tbody>
    //       {data.map((menu) => (
    //         <tr key={menu.id_menu}>
    //           <td>{menu.id_menu}</td>
    //           <td>{menu.nama}</td>
    //           <td>{menu.harga}</td>
    //           <td>{menu.stok}</td>
    //           <td>
    //             <CombinedImage
    //               imageData={Buffer.from(menu.gambar.data).toString("base64")}
    //             />
    //           </td>
    //         </tr>
    //       ))}
    //     </tbody>
    //   </table>
    // </div>
  );
};

export default AdminDashboard;
