import Head from 'next/head'
import Image from 'next/image'
import { GiHamburgerMenu } from 'react-icons/gi'
import { MdLogin } from 'react-icons/md'

export default function Home() {
  return (
    <>
      <Head>
        <title>Depot Sarigading</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <header className='bg-white'>
          <nav className='mx-auto flex max-w-7xl items-center justify-between p-6 lg:px-8'>
            <div className='flex'>
              <a className=' -m-1.5 p-1.5'>
                <span className='sr-only'>Depot Sarigading</span>
                <Image src='/sarigading.png' className='w-auto h-16' alt='' width='100' height='100'/>
              </a>
            </div>
            {/* <div className='flex lg:hidden'>
              <button
              type='button'
              className='-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700'
              >
                <span className='sr-only'>Open main menu</span>
                <GiHamburgerMenu className='h-6 w-6' aria-hidden='true'/>
              </button>
            </div> */}
            <div className='flex gap-4'>
            <a className='text-lg mx-4 font-semibold leading-6 text-gray-900'>
              Home
            </a>
            <a className='text-lg mx-4 font-semibold leading-6 text-gray-900'>
              Menu
            </a>
            </div>
              <button className='text-lg flex items-center mx-4 font-semibold leading-6 text-gray-900'>
                <MdLogin className='mx-1'/>
                Login
              </button>
          </nav>
        </header>
        <section className='bg-gray-700 w-full'>
          <div className='m-auto grid grid-cols-2 gap-2'>
            <div className='flex flex-col text-white justify-center items-start m-16'>
              <h1 className='text-6xl font-bold py-3'>The Delicious Food</h1>
              <h1 className='text-6xl font-bold py-3'>and Tasty Meal</h1>
              <p className='w-[70%]'>
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Qui aliquid necessitatibus atque?</p>
              <button className='bg-orange-500 p-2 rounded-md border border-white my-8'>See Menu</button>
            </div>
            <div>
              <Image src='/chicken.png' alt='' width='900' height='900'/>
            </div>
          </div>
        </section>
      </main>
    </>
  )
}
